# Generated by Django 3.1 on 2020-09-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_sup_bus_name', models.CharField(max_length=256)),
                ('p_sup_full_name', models.CharField(max_length=256)),
                ('p_sup_email', models.EmailField(max_length=254)),
                ('p_sup_phone', models.CharField(blank=True, max_length=256)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('postal_code', models.CharField(blank=True, max_length=256)),
                ('country', models.CharField(blank=True, max_length=256)),
                ('s_sup_bus_name', models.CharField(max_length=256)),
                ('s_sup_full_name', models.CharField(max_length=256)),
                ('s_sup_email', models.EmailField(max_length=254)),
                ('s_sup_phone', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
