# Generated by Django 3.1 on 2020-09-28 06:36

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierregistration',
            old_name='address_1',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='supplierregistration',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='supplierregistration',
            name='p_sup_full_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='supplierregistration',
            name='s_sup_full_name',
            field=models.CharField(max_length=256),
        ),
    ]
