# Generated by Django 3.1 on 2020-09-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200928_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierregistration',
            name='p_sup_phone',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='supplierregistration',
            name='postal_code',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='supplierregistration',
            name='s_sup_phone',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
